export const lightTheme = {
    primaryColor: '#1890ff',
    applicationBackground: '#E3E8EE',
    applicationColor: '#444',
    backgroundColor: '#fff',
    borderBoxBgColor: '#eee',
    color: '#444',
    borderColor: '#eee',
    inputBorderColor: '#eee',
    boxShadowColor: '#aaa',
    opacity: 1,
    titleColor: '#444',
    subTitleColor: '#777',
    textShadowColor: '#aaa',
    tableHoverColor: '#acc3e6',
    tableHoverFontColor: '#000',
}

export const darkTheme = {
    primaryColor: '#1890ff',
    applicationBackground: '#191E1D',
    applicationColor: '#ddd',
    backgroundColor: 'rgba(121, 140, 173, 0.3)',
    borderBoxBgColor: '#001529',
    color: '#eeeeee',
    borderColor: '#5e85a3',
    inputBorderColor: 'rgba(121, 140, 173, 0.3)',
    boxShadowColor: '#001529',
    opacity: 0.3,
    titleColor: '#ddd',
    subTitleColor: '#aaa',
    textShadowColor: '#aaa',
    tableHoverColor: '#001529',
    tableHoverFontColor: '#fff',
}